### PR TITLE
Fix(--strip-embed-comment): Fix process exiting with flag...

### PR DESCRIPTION
**Pull request by mrinalini-m**
...and write output to file without source comments

### CODE REVIEW

**Comment by zakhenry** [comment]
Hey @mrinalini-m good catch, I think the logic to make sure the log output goes to stderr is getting a little complex - it might be better for us to have a logError variant of the log function that ensures for the exiting cases that output goes to stderr. What do you reckon?

**Comment by mrinalini-m** [comment]
That's a good idea. Maybe add support for preserving chalk color for stderr logs with `--color` flag. https://github.com/chalk/chalk#chalkstderr-and-chalkstderrsupportscolor

**Comment by zakhenry** [comment]
Hey @mrinalini-m thanks again for your PR - I've ended up taking your suggestions on board and implemented the fix in #49 as there was a few related things to bundle. I realised the root cause of the issue was that I had insufficient testing, so I've add Ava to the project which gives nice snapshot testing which is a good fit for this kind of repo.

**Pull request closed without merging**
