### PR TITLE
Added support for css

### PR DESCRIPTION
**Pull request by PiyushXCoder**

### CODE REVIEW

**Comment by zakhenry** [comment]
Sorry for the delay on this - the code looks good but I think you're missing something in the test as I'd expect `test/fixtures/fixture.md` to have the css embedded

**Comment by PiyushXCoder** [comment]
Ok i am adding it..

**Comment by PiyushXCoder** [comment]
I have pushed the changes! Please merge it. I depend on this library for my college lab assignments.

**Comment by itihon** [comment]
Will there be a release with this feature added? Why the [action](https://github.com/zakhenry/embedme/actions/runs/11204397936) triggered by pushing this PR was cancelled?

**Pull request merged**
