### PR TITLE
feat(Language Support): Add JSX and TSX

### PR DESCRIPTION
**Pull request by aziaziazi**
Added JSX and TSX support.
Resolves https://github.com/zakhenry/embedme/issues/62.

### CODE REVIEW

**Comment by aziaziazi** [comment]
Hi @zakhenry ! Could you help me with the contribution process ? I've seen https://github.com/zakhenry/embedme/pull/54 but can't figure out in what orders the commands need to be run.
Thanks :)

**Comment by zakhenry** [comment]
Hi @aziaziazi I'm a bit confused as it looks like you've done all the right things, and it seems to be correct when I run the same commands Travis is running locally with your branch. I'll dig deeper

**Comment by zakhenry** [comment]
Ah ok it looks like something is just weird with the pre-merge result that travis is doing, the commit by itself is okay. I'll merge and clean up anything that broke

**Comment by aziaziazi** [comment]
Great ! Thanks for quick reply and for your lib. I can easely embed JSX now  🥳

**Comment by zakhenry** [comment]
No problem, thanks for the contribution 🎉

**Pull request merged**
