### PR TITLE
Added support for Arduino sketches (.ino)

### LINKED ISSUE #52: Request: Support for .ino files (Arduino sketches)
Hi Zak,

thanks for this great tool - one I was looking for for a long time.

I'm currently documenting some Arduino libraries and I use your tool to embed the example code into the readme. It works perfectly but spits out a warning of course:
```
Embedding...
Skipped 0 files ignored in '.gitignore'
  Analysing README.md...
   README.md#L5-L48 Embedded 40 lines from file examples/lcdpong-butenc/lcdpong-butenc.ino#L20-L59
   README.md#L67-L83 Unsupported file extension [c++], supported extensions are txt, ts, js, scss, rust, java, cpp, c, html, xml, md, yaml, json, json5, py, bash, sh, go, objectivec, php, cs, swift, rb, kotlin, scala, cr, puml, mermaid, cmake, proto, sql, hs, skipping code block
   README.md#L122-L129 No code extension detected, skipping code block...
   README.md#L137-L139 No code extension detected, skipping code block...
   README.md#L140-L141 Code block is empty & no preceding embedme comment, skipping...
   README.md#L144-L150 No code extension detected, skipping code block...
  Writing README.md with embedded changes.
```
The embedme-code was
``````Markdown
```cpp
// examples/lcdpong-butenc/lcdpong-butenc.ino#L20-L59
```
``````
The `.ino` are Arduino sketches and are plain C++, perhaps this could be implemented as an alias or so?

### PR DESCRIPTION
**Pull request by elektronikworkshop**
Hi Zak,

I tried to add Arduino sketch support myself (since you encouraged me doing so in the readme :) ). But I haven't tested it because I'm completely new to typescript. Perhaps you could give me a one liner how to test this locally with node.

Closes #52

### CODE REVIEW

**Comment by elektronikworkshop** [comment]
I'm fighting with the CI :)

**Comment by elektronikworkshop** [comment]
Damn, I don't get it to pass CI - seems that I need some help. I read the commits of other contributions like [this one](https://github.com/zakhenry/embedme/pull/41/files) and can't identify any differences. I virtually used C++ as template and copy pasted everything.

**Comment by zakhenry** [comment]
Hi @elektronikworkshop thanks for the PR, sorry I couldn't help out sooner; I've been away on holiday. You were pretty much there, the only thing that needed doing was running `yarn test:update`. To explain further, this repo uses snapshot testing which takes a sample file and snapshots both the stdoutput from embedme and the resulting file. When adding new capabilities, the snapshots need to be regenerated. This is a bit weird I admit, but it does make for an easy code review of what has actually changed in behavior.

**Comment by elektronikworkshop** [comment]
Yay! Thanks a lot!

Ironically I started hacking TypeScript after fiddling with your source - vscode-arduino annoyed me badly. So I took the plunge and now I understand the npm workflow much better.

Regards!

**Pull request merged**
